baseURL: "https://andreapadricelli.dev"
title: "Andrea Padricelli"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "My personal site and blog"
    author: Andrea Padricelli

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: Andrea Padricelli
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi"
        Content: >
            Welcome to my site!
    socialIcons:
        - name: github
          url: "https://github.com/ElderTugBoat786"
        - name: linkedin
          url: "https://www.linkedin.com/in/ElderTugBoat786"
        - name: RsS
          url: "index.xml"

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
        disableInlineCSS: true
